### PR TITLE
Add ISP

### PR DESCRIPTION
**Pull request by shihabcsedu09**

### CODE REVIEW

**Comment by imsazzad** [comment]
I like the example (y).
One feedback: are we missing the dry principle?
to be specific -> see creditLocalAmount() method

**Comment by shihabcsedu09** [comment]
> I like the example (y).
> One feedback: are we missing the dry principle?
> to be specific -> see creditLocalAmount() method

@imsazzad  implementation of credit local amount can be different for different types of account. In this case they are same. 

Also what is your alternative solution?

**Comment by imsazzad** [comment]
> > I like the example (y).
> > One feedback: are we missing the dry principle?
> > to be specific -> see creditLocalAmount() method
> 
> @imsazzad implementation of credit local amount can be different for different types of account. In this case they are same.
> 
> Also what is your alternative solution?

well if this is the same for all accounts it could be in the base class. AND If not the same,  we can use strategy pattern as far as I understood.

**Comment by shihabcsedu09** [comment]
@imsazzad hmm. For this scope i thik i we can ignore this for now?

**Comment by imsazzad** [comment]
> @imsazzad hmm. For this scope i thik i we can ignore this for now?

hmm, okay

**Pull request merged**
